name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onefile --distpath exe/ app.py

      - name: Build Docker image
        run: docker build -t todolist .

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: welyson
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push todolist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: TodoList
          path: exe/app.exe



